"""empty message

Revision ID: 604d0e46c139
Revises: 870208d49f6b
Create Date: 2022-03-07 13:21:35.368583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604d0e46c139'
down_revision = '870208d49f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
